version: 2

project_name: sopsy

before:
  hooks:
    - go mod tidy

builds:
  - id: sopsy
    main: ./cmd/sopsy
    binary: sopsy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: "^(feat).*"
      order: 0
    - title: Bug Fixes
      regexp: "^(fix|bug).*"
      order: 1
    - title: Documentation
      regexp: "^(docs).*"
      order: 2
    - title: Maintenance
      regexp: "^(chore|ci|test|style|refactor).*"
      order: 3
    - title: Others
      order: 999
  filters:
    exclude:
      - "^Merge"

brews:
  - name: sopsy
    repository:
      owner: enbiyagoral
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/enbiyagoral/sopsy"
    description: "SOPS profile manager - manage age key profiles for encryption"
    license: "Apache-2.0"
    install: |-
      bin.install "sopsy"
    caveats: |-
      To enable shell integration, run:
        sopsy init zsh
      
      Then restart your terminal or run:
        source ~/.zshrc
    test: |-
      system "#{bin}/sopsy", "--help"

release:
  github:
    owner: enbiyagoral
    name: sopsy
  draft: false
  prerelease: auto
